/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanilhasRouteImport } from './routes/planilhas'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportsIndexRouteImport } from './routes/transports.index'
import { Route as TransportsIdRouteImport } from './routes/transports.$id'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as ChecklistsHistoricoRouteImport } from './routes/checklists.historico'
import { Route as ChecklistsIdRouteImport } from './routes/checklists.$id'
import { Route as FinancialClientsNameRouteImport } from './routes/financial.clients.$name'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanilhasRoute = PlanilhasRouteImport.update({
  id: '/planilhas',
  path: '/planilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportsIndexRoute = TransportsIndexRouteImport.update({
  id: '/transports/',
  path: '/transports/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportsIdRoute = TransportsIdRouteImport.update({
  id: '/transports/$id',
  path: '/transports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsHistoricoRoute = ChecklistsHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ChecklistsRoute,
} as any)
const ChecklistsIdRoute = ChecklistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChecklistsRoute,
} as any)
const FinancialClientsNameRoute = FinancialClientsNameRouteImport.update({
  id: '/clients/$name',
  path: '/clients/$name',
  getParentRoute: () => FinancialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/planilhas': typeof PlanilhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/historico': typeof ChecklistsHistoricoRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports/': typeof TransportsIndexRoute
  '/financial/clients/$name': typeof FinancialClientsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/planilhas': typeof PlanilhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/historico': typeof ChecklistsHistoricoRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports': typeof TransportsIndexRoute
  '/financial/clients/$name': typeof FinancialClientsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/planilhas': typeof PlanilhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/historico': typeof ChecklistsHistoricoRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports/': typeof TransportsIndexRoute
  '/financial/clients/$name': typeof FinancialClientsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklists'
    | '/collections'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/login'
    | '/partners'
    | '/planilhas'
    | '/reset-password'
    | '/settings'
    | '/social'
    | '/users'
    | '/checklists/$id'
    | '/checklists/historico'
    | '/d/$token'
    | '/transports/$id'
    | '/transports/'
    | '/financial/clients/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/collections'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/login'
    | '/partners'
    | '/planilhas'
    | '/reset-password'
    | '/settings'
    | '/social'
    | '/users'
    | '/checklists/$id'
    | '/checklists/historico'
    | '/d/$token'
    | '/transports/$id'
    | '/transports'
    | '/financial/clients/$name'
  id:
    | '__root__'
    | '/'
    | '/checklists'
    | '/collections'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/login'
    | '/partners'
    | '/planilhas'
    | '/reset-password'
    | '/settings'
    | '/social'
    | '/users'
    | '/checklists/$id'
    | '/checklists/historico'
    | '/d/$token'
    | '/transports/$id'
    | '/transports/'
    | '/financial/clients/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  DocumentsRoute: typeof DocumentsRoute
  FeedbackRoute: typeof FeedbackRoute
  FinancialRoute: typeof FinancialRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PlanilhasRoute: typeof PlanilhasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  UsersRoute: typeof UsersRoute
  DTokenRoute: typeof DTokenRoute
  TransportsIdRoute: typeof TransportsIdRoute
  TransportsIndexRoute: typeof TransportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planilhas': {
      id: '/planilhas'
      path: '/planilhas'
      fullPath: '/planilhas'
      preLoaderRoute: typeof PlanilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transports/': {
      id: '/transports/'
      path: '/transports'
      fullPath: '/transports/'
      preLoaderRoute: typeof TransportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transports/$id': {
      id: '/transports/$id'
      path: '/transports/$id'
      fullPath: '/transports/$id'
      preLoaderRoute: typeof TransportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/historico': {
      id: '/checklists/historico'
      path: '/historico'
      fullPath: '/checklists/historico'
      preLoaderRoute: typeof ChecklistsHistoricoRouteImport
      parentRoute: typeof ChecklistsRoute
    }
    '/checklists/$id': {
      id: '/checklists/$id'
      path: '/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof ChecklistsIdRouteImport
      parentRoute: typeof ChecklistsRoute
    }
    '/financial/clients/$name': {
      id: '/financial/clients/$name'
      path: '/clients/$name'
      fullPath: '/financial/clients/$name'
      preLoaderRoute: typeof FinancialClientsNameRouteImport
      parentRoute: typeof FinancialRoute
    }
  }
}

interface ChecklistsRouteChildren {
  ChecklistsIdRoute: typeof ChecklistsIdRoute
  ChecklistsHistoricoRoute: typeof ChecklistsHistoricoRoute
}

const ChecklistsRouteChildren: ChecklistsRouteChildren = {
  ChecklistsIdRoute: ChecklistsIdRoute,
  ChecklistsHistoricoRoute: ChecklistsHistoricoRoute,
}

const ChecklistsRouteWithChildren = ChecklistsRoute._addFileChildren(
  ChecklistsRouteChildren,
)

interface FinancialRouteChildren {
  FinancialClientsNameRoute: typeof FinancialClientsNameRoute
}

const FinancialRouteChildren: FinancialRouteChildren = {
  FinancialClientsNameRoute: FinancialClientsNameRoute,
}

const FinancialRouteWithChildren = FinancialRoute._addFileChildren(
  FinancialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  DocumentsRoute: DocumentsRoute,
  FeedbackRoute: FeedbackRoute,
  FinancialRoute: FinancialRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PlanilhasRoute: PlanilhasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  UsersRoute: UsersRoute,
  DTokenRoute: DTokenRoute,
  TransportsIdRoute: TransportsIdRoute,
  TransportsIndexRoute: TransportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
