/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportsIndexRouteImport } from './routes/transports.index'
import { Route as TransportsIdRouteImport } from './routes/transports.$id'
import { Route as DTokenRouteImport } from './routes/d.$token'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportsIndexRoute = TransportsIndexRouteImport.update({
  id: '/transports/',
  path: '/transports/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportsIdRoute = TransportsIdRouteImport.update({
  id: '/transports/$id',
  path: '/transports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/financial': typeof FinancialRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports/': typeof TransportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/financial': typeof FinancialRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports': typeof TransportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/financial': typeof FinancialRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/users': typeof UsersRoute
  '/d/$token': typeof DTokenRoute
  '/transports/$id': typeof TransportsIdRoute
  '/transports/': typeof TransportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/documents'
    | '/financial'
    | '/login'
    | '/settings'
    | '/social'
    | '/users'
    | '/d/$token'
    | '/transports/$id'
    | '/transports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/documents'
    | '/financial'
    | '/login'
    | '/settings'
    | '/social'
    | '/users'
    | '/d/$token'
    | '/transports/$id'
    | '/transports'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/documents'
    | '/financial'
    | '/login'
    | '/settings'
    | '/social'
    | '/users'
    | '/d/$token'
    | '/transports/$id'
    | '/transports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  DocumentsRoute: typeof DocumentsRoute
  FinancialRoute: typeof FinancialRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  UsersRoute: typeof UsersRoute
  DTokenRoute: typeof DTokenRoute
  TransportsIdRoute: typeof TransportsIdRoute
  TransportsIndexRoute: typeof TransportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transports/': {
      id: '/transports/'
      path: '/transports'
      fullPath: '/transports/'
      preLoaderRoute: typeof TransportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transports/$id': {
      id: '/transports/$id'
      path: '/transports/$id'
      fullPath: '/transports/$id'
      preLoaderRoute: typeof TransportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  DocumentsRoute: DocumentsRoute,
  FinancialRoute: FinancialRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  UsersRoute: UsersRoute,
  DTokenRoute: DTokenRoute,
  TransportsIdRoute: TransportsIdRoute,
  TransportsIndexRoute: TransportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
