// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The anon/publishable key is not a secret (it's meant to run in the browser,
// and data access is enforced by RLS) — it's safe to fall back to a known
// default here so a missing VITE_ build-time env var never takes the whole
// app down. Prefer the env var when the build pipeline provides one.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qhbjqmgcftsffgsukuxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYmpxbWdjZnRzZmZnc3VrdXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NzgxODQsImV4cCI6MjA5NDI1NDE4NH0.jnzw0efWtlAxmX_I8F5NU0huw29KKYIaMzGBbcsHa7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});